puts "Heelo Github! Octocats are amazing"
puts "something"
puts "Nithya"
puts "Keelin"
puts "Nikki"
puts "Mihir"
puts "Elijah"
puts "Bryce"
puts "David"
puts "Charlie"
puts "Motts"
puts "Jett"
puts "Derek"
puts "Ben"
puts "Mr.Padjen"